### ISSUE TITLE
Initialise sdk with custom plugin directory

### ISSUE THREAD

**Issue by Stupremee** [WootingKb/wooting-analog-sdk#22]
It would be really helpful for me to have a method in `wooting-analog-wrapper` that allows me to overwrite the plugin directory because I'm on NixOS and `/usr/local/share` is not a thing here.

I'm happy to open a PR!

**Comment by simon-wh** [comment]
Hi, this was something that was originally possible, through the use of an environment variable that controlled directories that would be searched for plugins. However, this was removed due to security concerns.

I'm not sure if having the plugin directory being controlled by `wooting-analog-wrapper` would be a sensible choice given that it puts the changing of the directory in the hands of the app developer. As opposed to a system-wide configuration that this seems more appropriate to as all plugins would be in a different place. Having it in the wrapper would mean only apps that keep NixOS in mind would work properly in NixOS.

It seems to me that it would make more sense to have an alternative build that uses a different path for searching for plugins or a runtime check which uses a different directory when on NixOS.

**Comment by Stupremee** [comment]
That would work too yes. You could set an environment variable at build time that will change the path. Seems like a good solution

**Comment by Stupremee** [comment]
@simon-wh Would you be fine with me opening a PR that will introduce a build-time `WOOTING_PLUGIN_DIR` environment variable?

**Comment by simon-wh** [comment]
> @simon-wh Would you be fine with me opening a PR that will introduce a build-time `WOOTING_PLUGIN_DIR` environment variable?

Yeah that'd be fine, good luck :+1:
